name: Deploy form email api

on:
  push:
    branches: [ 6-email-form-upgrade ]
  workflow_dispatch:
  
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  Email-Form-API-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          set-safe-directory: 'true'

      - name: Pull latest submodule commits
        run: git submodule update --remote --recursive

      - name: Update worker default name
        run: jq '.name = "portfolio-contact-api"' ./form-email-api/api/wrangler.jsonc > ./form-email-api/temp.jsonc && mv ./form-email-api/temp.jsonc ./form-email-api/api/wrangler.jsonc

      - name: Override schema.toml
        run: mv ./form-email-api/schema.toml ./form-email-api/api/schema.toml

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Node dependencies
        uses: actions/cache@v4 
        with:
          path: ./form-email-api/api/node_modules
          key: node-modules-${{ hashFiles('**/bun.lockb', '**/bun.lock') }}

      - name: Install dependencies
        run: bun ci
        working-directory: ./form-email-api/api

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./form-email-api/api