name: Deploy form email api

on:
  push:
    branches: [ 6-email-form-upgrade ]
  workflow_dispatch:
  
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  Email-Form-API-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Update worker default name
        run: jq '.name = "portfolio-contact-api"' ./form-email-api/api/wrangler.jsonc > ./form-email-api/temp.jsonc && mv ./form-email-api/temp.jsonc ./form-email-api/api/wrangler.jsonc

      - name: List files to find schema.toml
        run: |
          echo "=== Root Directory ==="
          ls -R .

      - name: Override schema.toml
        run: mv ./form-email-api/schema.toml ./form-email-api/api/schema.toml

      - run: cat ./form-email-api/api/schema.toml