name: Deploy portfolio to Github Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  Pages-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Node dependencies
        uses: actions/cache@v3 
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('bun.lock') }}

      - name: Install dependencies
        run: bun install

      - name: Create sqlite database
        run: sqlite3 ./db/data.db < ./db/setup.sql

      # Exports all public Github repos, from owner, into a JSON file
      - name: Fetch repositories details
        run: |
          gh repo list ${{ github.repository_owner }} --limit 1000 --source --public --json description,homepageUrl,id,languages,description,repositoryTopics,name,primaryLanguage,repositoryTopics,url > ./db/repos.json
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Seed Github repositories into project table
        run: bun ./db/seed_repositories.ts
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          FEATURED_PROJECTS: ${{ vars.FEATURED_PROJECTS }}


      - name: Build
        run: bun run build
        env:
          PUBLIC_GITHUB_USERNAME: ${{ github.repository_owner }}
          PUBLIC_CONTACT_EMAIL: ${{ vars.EMAIL }}
          PUBLIC_LINKEDIN_USERNAME: ${{ vars.LINKEDIN || '' }}

          PUBLIC_AVAILABILITY: ${{ vars.AVAILABLE || 'false' }}

          PUBLIC_LOCATION_TEXT: ${{ vars.LOCATION_TEXT || '' }}
          PUBLIC_LOCATION_URL: ${{ vars.LOCATION_URL || '' }}

          PUBLIC_BOTPOISON_KEY: ${{ vars.BOTPOISON_KEY }}
          

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './.dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4